# Generated by Django 3.1.4 on 2020-12-14 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='QueueUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image_url', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('hotel', models.CharField(max_length=150)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('vacationer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queuedapi.queueuser')),
            ],
        ),
        migrations.CreateModel(
            name='RideReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_id', models.CharField(max_length=100)),
                ('ride_name', models.CharField(max_length=200)),
                ('rating', models.IntegerField(null=True)),
                ('review', models.TextField(null=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queuedapi.queueuser')),
            ],
        ),
        migrations.CreateModel(
            name='RideItinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField(null=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queuedapi.itinerary')),
            ],
        ),
        migrations.CreateModel(
            name='RideFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_id', models.CharField(max_length=100)),
                ('ride_name', models.CharField(max_length=200)),
                ('favorite', models.BooleanField(default=False)),
                ('vacationer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queuedapi.queueuser')),
            ],
        ),
        migrations.AddField(
            model_name='itinerary',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queuedapi.trip'),
        ),
    ]
